### ISSUE TITLE
421 errors and deliverability problems

### ISSUE THREAD

**Issue by omjeremy** [forwardemail/free-email-forwarding#193]
When sending from Gmail or G Suite to domains setup with forwardemail I'm having problems whith receiving emails. I've been getting no responses either way when sending test emails so I figured perhaps it's been rejected due to content. I sent a real email message from my g suite account and received a 421 timeout - closing connection error. The domain forwarded with this service is being forwarded to a Gmail account. 

When sending emails from outlook mail to the forward domain I have no issues with receiving them.

**Comment by omjeremy** [comment]
Adding more info... For the g suite sent emails the errors are the following

`421 SPF validation failed with result "permerror" and explanation "SPF Permanent Error: Two or more type TXT spf records found." - if you need help please forward this email to support@forwardemail.net or visit https://forwardemail.net`

The domain does not have more than one spf record. It does have three other TXT records but they have nothing to do with spf.

**Comment by niftylettuce** [comment]
We need to know the domain to help you, feel free to email it over so we can help.

**Comment by omjeremy** [comment]
The domain is valman.design

Thanks!

**Comment by niftylettuce** [comment]
OK I see what the issue is, it's `valman.cl` DNS records that are bad.

```sh
dig valman.cl txt

; <<>> DiG 9.8.3-P1 <<>> valman.cl txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59900
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;valman.cl.			IN	TXT

;; ANSWER SECTION:
valman.cl.		300	IN	TXT	"v=spf1 include:_spf.google.com ~all"
valman.cl.		300	IN	TXT	"v=spf1 include:spfa.mailendo.com ~all"
valman.cl.		300	IN	TXT	"facebook-domain-verification=1ofr57tfc901bc8vh3n3zh539y93jk"
valman.cl.		300	IN	TXT	"google-site-verification=a3pMa4eR7moR2XVnGe91suHoxRy5rqNbaVMmMTcCRh"
```

As you can see there are two SPF records.  There should only be one.  If you own `valman.cl` please concatenate them to be `v=spf1 include:_spf.google.com include:spfa.mailendo.com ~all`.

Once done, purge TXT record cache using Cloudflare DNS tool <https://1.1.1.1/purge-cache/>.

**Comment by omjeremy** [comment]
I think there was a misunderstanding. The domain is valman.design and not
valman.cl

The latter is using g suite

**Comment by omjeremy** [comment]
Ahhh oops misunderstood your email!

**Comment by niftylettuce** [comment]
No problem - I recommend waiting 1-2 hours before testing again once that's fixed.   Feel free to email me directly at niftylettuce@gmail.com if you still have issues.  Would love to help you out further.  Happy new year, too! 🎉

**Comment by omjeremy** [comment]
Thank you so much! I've confirmed that everything works now. You rock!
Happy new year

**Comment by niftylettuce** [comment]
To anyone that still encountered this issue, there was one more bug due to host normalization that needed fixed.  It's all resolved now though, was pesky to track down! 🎉 

Any further issues, questions, or feature requests, please let us know.

v6.1.4 has been released and deployed, which fixed this issue through some added "host normalization" logic.
