### ISSUE TITLE
Add manual whitelist

### ISSUE THREAD

**Issue by niftylettuce** [forwardemail/free-email-forwarding#23]

**Comment by bdeeming** [comment]
Hi @niftylettuce, thanks for the great project & service!
I've recently run into a scenario where legitimate emails from a newsletter I signed up for was (I'm guessing) spam-rejected. There was no way to know/verify it happened however, or recover from it, since there is no spam folder to check.
I'm assuming that scenario is what this ticket is more or less targeting?
Would it also be feasible to have an option to forward all spam emails to the destination address, but with a `[SPAM]` prefix in the subject (or similar thing that a filter could be setup with to send them to the spam folder)?

**Comment by niftylettuce** [comment]
The most obvious reason why you did not receive the email is because the person who is sending the newsletter did not configure their domain name properly.  They are most likely missing either DKIM or SPF record on their domain (at least one is required, otherwise it's incredibly easy to spoof email as being from them).  You may want to reach out manually to the person running the newsletter and let them know.

**Comment by niftylettuce** [comment]
A lot has changed in the past few months to improve deliverability, perfect DMARC + friendly from rewrite, and I am soon to release SpamScanner implementation as well.
