### ISSUE TITLE
Hashing support

### ISSUE THREAD

**Issue by niftylettuce** [forwardemail/free-email-forwarding#3]
To keep forwarding addresses anonymous, we need to setup hashing that can only be decrypted by forwardemail.net, to generate a hash, you will enter your email address to forward to at forwardemail.net and a hash will be displayed to copy/paste

**Comment by kitling** [comment]
this wouldn't be hashing, this would be encryption of some sort. similarly to #2, I'd suggest a PKI scheme (PGP?) to encrypt the target email in a way that only you can decrypt it for these private forwarding things.

**Comment by niftylettuce** [comment]
Yeah that's precisely what I meant, I was just referring to hash as an
encrypted or obfuscated string, so PGP/AES or something

**Comment by kitling** [comment]
oh, could maybe even use your existing ssl key, but that'd require using a different package and scheme and such. openpgp is nice because it has already taken into account everything and I don't need to put much effort into making it secure.

I've got working code that'll work as a base for both this and password storage for #2 now using openpgpjs (https://runkit.com/embed/hx1b3r4ej81j)

getConfig is the new function that we'd start using. the cfgstr parameter is used to specify which configuration entry we want (so we can have a seperate one for 'forward-email' and 'forward-auth', say) It returns everything after the '='. If the first character after '=' is '!', then if does a base64 decode of everything else, and runs it through openpgp decryption before returning it. In this way, any config item can be (optionally or exclusively) encrypted if it uses getConfig.

To generate an obscured email for use with this, first you pgp encrypt w/o ascii armor, and then you base64. example code for this is included (and is also what I used to generate the record on my test domain.

The keys attached aren't tied to anything important, just used for this experimentation (also generated with openpgpjs)

**Comment by kitling** [comment]
I should note that no scheme will really work if we want to prevent dns mitm causing issues and that I'm not all that familiar with javascript or with handling errors w/ promises, so you should take a good look at getConfig before using it yourself.

**Comment by BassemN** [comment]
Thanks for your great service :)
We hope to see this feature implemented very soon

**Comment by aaronstuder** [comment]
I also want this =)

Following...

**Comment by alamothe** [comment]
Same! 

Appreciate the open source, but I would definitely pay for this service (forwarding + API to create/remove aliases). I tried forwardmx.io but it's too slow to forward email (up to 20min)

**Comment by aaronstuder** [comment]
@alamothe I provide a service like this

**Comment by thisismydesign** [comment]
@aaronstuder could you send me a mail about that service?

**Comment by codinghedgehog** [comment]
This is a very good point.  I just started using this and love it, but having the target email in DNS isn't great.  Has any progress been made on this front?

**Comment by niftylettuce** [comment]
I promise it will be released asap.

**Comment by Tburg10** [comment]
Any update.  Would like to use this service since my Registrar is getting rid of free hosted email with my domain.  But I dont want a bunch of spam!

**Comment by Tburg10** [comment]
Bit of a workaround if anyone is interested... I setup a 2nd gmail account like hfkjfkhfkkj@gmail.com, forwarded it to my main email and set up a filter so that any email sent to hfkjfkhfkkj@gmail.com gets deleted immediately.

**Comment by niftylettuce** [comment]
I have been dedicating a lot of time to this lately.  Just a bit more patience, and I promise I will have exactly what you guys want and more 👍 😄

**Comment by tracker1** [comment]
@Tburg10 FYI, for what it's worth, Google domains does free mail forwarding.

**Comment by Tburg10** [comment]
Thanks for the info. I just need a temp solution. I don't really need the
domain anymore but I was too lazy to change everything when it came up for
renewal in August. Then go daddy decided to get rid of free email with
their domain. So I just need a solution for a a little while. At some point
I'll just set up another Gmail.

**Comment by tracker1** [comment]
@Tburg10 gotcha... just figured I'd mention it... probably my fav feature of google for domain registration, I have a few older domains I really didn't want a mail server for.  Using this site/app for one I have where dns is controlled on digital ocean.

**Comment by niftylettuce** [comment]
You can now have privacy and hidden records using our Enhanced Protection or Team Plans at https://forwardemail.net/features.
